### ISSUE TITLE
Cant build project

### ISSUE THREAD

**Issue by vyshka** [Jagailo/YetAnotherKeyDisplayer#1]
Cant build project coz of 
`Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to find manifest signing certificate in the certificate store.	YAKD			
`
This error probably throw coz solution explorer said that YAKD_TemporaryKey.pfx file does not exist. I think you should update your .gitignore or investigate why file is not uploaded to repo.

**Comment by vyshka** [comment]
#2 i create pull request so submit it and then re-push project to repo

**Comment by vyshka** [comment]
Still get same error:
`error MSB3323: Unable to find manifest signing certificate in the certificate store.`
1 of possible solution is ot disable sign the ClickOnce manifests in project properties.
![image](https://user-images.githubusercontent.com/15892729/42761833-57f4a556-8917-11e8-8cb4-02fbc28b5852.png)

**Comment by Jagailo** [comment]
Try to download last build from "Dev" branch, and check it.

![image](https://user-images.githubusercontent.com/10468120/42767284-37d395b2-8925-11e8-8502-052f0cae38d4.png)
