### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by codysechelski** [Jagailo/YetAnotherKeyDisplayer#12]
It would be great if it could display "Mouse Wheel Up" or "Mouse Wheel Down" when scrolling.

USE CASE: I was trying to make a short video to illustrate what happens when you ctrl+scroll on a video. It was helpful for the viewer to see that my ctrl key was pressed, but it wasn't obvious in the video that I was scrolling.

Thanks!

**Comment by Jagailo** [comment]
Hello, actually this feature was implemented at first, but due to the long text, I abandoned it.
I can't use icons to show pressed keys, but I'll try to come up with something using font characters.

**Comment by codysechelski** [comment]
Thanks for the reply. Yeah, I could see how that would be super useful.

**Comment by mbilaldnc** [comment]
I really love your app and I would appreciate more if it had this feature. PLEASE BRING IT 🥰

**Comment by Jagailo** [comment]
This feature will be added in version 1.3.
The release is scheduled for April 10th.
