### ISSUE TITLE
Keep keys displaying for a while

### ISSUE THREAD

**Issue by LeonCheung** [Jagailo/YetAnotherKeyDisplayer#13]
Hi, first I have to say that this tool is really amazing, simple yet beautiful. May I share my two cents here?

1. Currently, when I press some key, it will immediately disappear after releasing it, sometimes it disappeared too soon to see what key is pressed exactly. So, maybe we can define a period of time before it disappears or being replaced by another key press?

2. Fade-out effect can be nice to have if possible.

3. For Shift/Ctrl/Alt/Win, in many cases, we don't care much about whether it's from L or R, so maybe there can be an option to decide whether or not it will distinguish both sides. So as Numpad keys.

That's my humble opinion for now, and can be considered as a feature request if you will. Again, It's a very amazing tool. Thanks so much.

**Comment by overdev93** [comment]
I agree, this program needs an option that the displayed keys should be displayed until the next one is pressed

**Comment by Jagailo** [comment]
Hello, thanks for your feedback.

1. This feature will be added in version 1.3. The release is scheduled for April 10th.
2. For technical reasons, this cannot be done.
3. Interesting idea, I'll think about it.

**Comment by Jagailo** [comment]
Version 1.3 is out.
