### ISSUE TITLE
Not working with RTSS if RTSS started befor YAKD

### ISSUE THREAD

**Issue by scumware** [Jagailo/YetAnotherKeyDisplayer#17]
I had reproduced this bug.
If RTSS started befor YAKD or RTSS started befor clicking RTSSRadioButton then RTSSHandler._osd will not initialized and _osd?.Update(text); does nothing.

**Comment by Jagailo** [comment]
It's fixed, but I don't want to release a new version with only 1 bug fix.
Not critical, changes in the dev branch.

**Comment by Jagailo** [comment]
The bug was fixed in version [1.4](https://github.com/Jagailo/YetAnotherKeyDisplayer/releases).
