### ISSUE TITLE
Request: Click-through the display

### ISSUE THREAD

**Issue by NohbdyAhtall** [Jagailo/YetAnotherKeyDisplayer#19]
I believe it would be quite worthwhile if the "window" displaying the keys could be given a checkbox for it to be **visible but not clickable**.

_(Secondary, off-topic)_ For extra style points, I think it'd be nifty if the window could optionally "pulse" in transparency/saturation/gradient/etc when a key is pressed.

**Comment by Jagailo** [comment]
To display the keys, a regular window without a frame is used. The only way to make it through-clickable is to make the window completely transparent. That is why in the current implementation the minimum transparency threshold is 0.01.

I'll think about this feature.

As for styles and transitions, that's out of my area of expertise.
If someone wants to do it - feel free to create pull request, I won't.

**Comment by Jagailo** [comment]
@NohbdyAhtall Hello, the click-through feature has been added in version [1.4](https://github.com/Jagailo/YetAnotherKeyDisplayer/releases). There is also an option to display the Key Displayer only when keys are pressed.
