### ISSUE TITLE
Minimize YAKD to the System Tray

### ISSUE THREAD

**Issue by zhx17787891171** [Jagailo/YetAnotherKeyDisplayer#23]
请问可以使yakd最小化在托盘吗？

**Comment by Jagailo** [comment]
Hello, thanks for your feedback.

Maybe I'll add it later. I can't promise anything.

All the best.

**Comment by Jagailo** [comment]
@zhx17787891171 Hello, the button to hide the main window in the tray has been added to version [1.4](https://github.com/Jagailo/YetAnotherKeyDisplayer/releases).
