### ISSUE TITLE
Why there is an “F22”

### ISSUE THREAD

**Issue by 1111HGH** [Jagailo/YetAnotherKeyDisplayer#24]
I just click a link in the wechat with the mouse without touching the keyboard, what happend
![bf8d96d6f34b912a92e1d194257cbe4](https://github.com/Jagailo/YetAnotherKeyDisplayer/assets/121378955/7b6ac9b0-0c45-4dc8-87b2-495367b6e0a4)

**Comment by Jagailo** [comment]
I don't know to be honest, apparently wechat generates a click of such a button.
