### ISSUE TITLE
L Ctrl + R Alt displayed instead of Alt Gr or R Alt

### ISSUE THREAD

**Issue by ed38** [Jagailo/YetAnotherKeyDisplayer#29]
Hello,

I press Alt Gr but "L Ctrl + R Alt" is displayed.
My config : Windows 11 (VM), french keyboard.

Thank you for your work,
Best regards
Ed

**Comment by Jagailo** [comment]
Hello Ed,
Thank you for using YAKD and actively participating in improving the project.

From [AltGr key](https://en.wikipedia.org/wiki/AltGr_key) page on Wikipedia:

> Windows interprets Ctrl+Alt as AltGr, to accommodate some compact keyboards like those of netbooks which have neither the AltGr key nor a right-hand Alt key. Because of this feature, Microsoft advises that Ctrl+Alt not be used as part of any application keyboard shortcut, as it would prevent typing the matching AltGr character on such keyboards.

Thus, Windows doesn't know that AltGr key exists and sees it as pressing two keys at once (Alt + Ctrl).
This cannot be fixed (perhaps Microsoft will fix this sometime in the future).

Have a great day.
