### ISSUE TITLE
Вывод только горячих клавиш

### ISSUE THREAD

**Issue by DmitryBerdnikov** [Jagailo/YetAnotherKeyDisplayer#3]
Сейчас нету опции "показывать только горячие клавиши"? Насколько сложно сделать такой функционал?

**Comment by Jagailo** [comment]
Добрый день, есть небольшая сложность в определение какие именно клавиши "горячие". Ведь для разных программ есть разные сочетания хоткеев, а в некоторых можно менять и добавлять горячии клавиши самостоятельно.

Не могли бы вы прояснить, что подразумевается под горячими клавишами?
Как вариант можно добавить новое окно с добавлением клавиш, которые будут отображаться/игнорироваться.

**Comment by Jagailo** [comment]
Закрываю по причине отсутствия дополнительных сведений.
