### ISSUE TITLE
[Feature Request] Horizontal alignment option

### ISSUE THREAD

**Issue by Barnacle** [Jagailo/YetAnotherKeyDisplayer#5]
It would be nice if there will be a "HorizontalAlignment" option (Left, Center, Right) for keysTextBlock in KeyDisplayerForm.
Because in some cases "only Center HorizontalAlignment" doesn't always look good.
Thanks.

**Comment by Jagailo** [comment]
Hello Barnacle,
I'll think about it, but don't wait for this feature in version 1.2, which I'm working on.
Unfortunately, I can’t allocate a lot of time for this project due to work.

**Comment by Jagailo** [comment]
Hi @Barnacle,
I just want to tell you that I accepted this request, and I'll add this feature in version 1.2.
Released somewhere in April.

Stay safe and all the best.

**Comment by Jagailo** [comment]
Added in [v.1.2](https://github.com/Jagailo/YetAnotherKeyDisplayer/releases/tag/v1.2).
