### ISSUE TITLE
Добавить кнопку которая бы фиксировала позицию OSD окошка.

### ISSUE THREAD

**Issue by IzoFox** [Jagailo/YetAnotherKeyDisplayer#7]
Добавить кнопку которая бы фиксировала позицию OSD окошка.
То есть, выставил окошко где тебе нужно и зафиксировал его кнопочкой или чекбоксом.

Программа классная. Спасибо 👍

**Comment by Jagailo** [comment]
Добрый день, извиняюсь за столь долгий ответ. Спасибо за Ваш отзыв.

Фиксация окна с кнопками - хорошая идея, думаю она будет добавлена в ближайшем релизе.

Всего вам доброго и не болейте.

**Comment by IzoFox** [comment]
Спасибо! И вам всего доброго. Здоровейте))

**Comment by Jagailo** [comment]
Добавил в релизе [1.2.1](https://github.com/Jagailo/YetAnotherKeyDisplayer/releases/tag/1.2.1).
